nome_cliente = input("Digite o nome do cliente: ")
dia_vencimento = input("Digite o dia do vencimento: ")
mes_vencimento = input("Digite o mes do vencimento: ")
valor_fatura = input("Digite o valor da fatura: ")
print("Olá,", nome_cliente)
print("A sua fatura com vencimento em", dia_vencimento, "de", mes_vencimento, "no valor de R$", valor_fatura, "está fechada.")
